#!/usr/bin/env python3
"""
LeanAI launcher installer.

Run ONCE from inside the repo::

    python install_launcher.py

It records THIS repo's location and creates a small ``leanai`` command on your
PATH, so you can type ``leanai`` from any folder and it starts LeanAI.

Why no disk scanning? Searching the whole drive on every launch is slow and
unreliable. This script already knows where it lives, so it captures the path
once — instant and dependable. If you move the repo later, just run this again.

It bakes in the Python interpreter you run it with (``sys.executable``), so run
this with the SAME ``python`` you normally use to start LeanAI, and the command
will use that exact environment (deps, venv, etc.).

Windows  -> %USERPROFILE%\\bin\\leanai.bat
macOS/Linux -> ~/.local/bin/leanai   (made executable)
"""

from __future__ import annotations

import os
import platform
import sys
from pathlib import Path
from typing import Optional, Tuple


def _is_windows(os_name: Optional[str] = None) -> bool:
    return "windows" in (os_name or platform.system()).lower()


def repo_root() -> Path:
    """The directory this script lives in = the LeanAI repo root."""
    return Path(__file__).resolve().parent


def launcher_dir(os_name: Optional[str] = None) -> Path:
    if _is_windows(os_name):
        base = os.environ.get("USERPROFILE") or str(Path.home())
        return Path(base) / "bin"
    return Path.home() / ".local" / "bin"


def launcher_path(os_name: Optional[str] = None) -> Path:
    name = "leanai.bat" if _is_windows(os_name) else "leanai"
    return launcher_dir(os_name) / name


def render_launcher(repo: Path, python_exe: str, os_name: Optional[str] = None) -> str:
    """The text of the generated launcher script."""
    if _is_windows(os_name):
        # CRLF line endings for a Windows .bat
        return (
            "@echo off\r\n"
            "rem LeanAI launcher - generated by install_launcher.py\r\n"
            "rem Re-run install_launcher.py if you move the repo.\r\n"
            f'cd /d "{repo}"\r\n'
            f'"{python_exe}" main.py %*\r\n'
        )
    return (
        "#!/usr/bin/env bash\n"
        "# LeanAI launcher - generated by install_launcher.py\n"
        "# Re-run install_launcher.py if you move the repo.\n"
        f'cd "{repo}" || exit 1\n'
        f'exec "{python_exe}" main.py "$@"\n'
    )


def on_path(directory: Path) -> bool:
    """True if `directory` is already on the PATH environment variable."""
    target = os.path.normcase(os.path.normpath(str(directory)))
    for part in os.environ.get("PATH", "").split(os.pathsep):
        if part and os.path.normcase(os.path.normpath(part)) == target:
            return True
    return False


def install(os_name: Optional[str] = None, python_exe: Optional[str] = None,
            write: bool = True) -> Tuple[Path, Path, Path, str]:
    """Create the launcher. Returns (repo, dir, launcher_path, content).

    `write=False` renders without touching disk (used by tests).
    """
    repo = repo_root()
    py = python_exe or sys.executable or "python"
    d = launcher_dir(os_name)
    path = launcher_path(os_name)
    content = render_launcher(repo, py, os_name)
    if write:
        d.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        if not _is_windows(os_name):
            os.chmod(path, 0o755)
    return repo, d, path, content


def main() -> None:
    repo, d, path, _ = install()
    win = _is_windows()
    print("LeanAI launcher installed.")
    print(f"  Repo:      {repo}")
    print(f"  Launcher:  {path}")
    print(f"  Python:    {sys.executable}")
    print()
    if on_path(d):
        print("  Done. Open a NEW terminal and type  leanai  from any folder.")
    else:
        print(f"  One more step: the folder {d} is not on your PATH yet, so")
        print("  `leanai` won't be found from other directories until you add it.")
        if win:
            print()
            print(f'    setx PATH "%PATH%;{d}"')
            print()
            print("  Then open a NEW terminal and type  leanai .")
        else:
            print()
            print(f'    echo \'export PATH="$PATH:{d}"\' >> ~/.bashrc')
            print("    source ~/.bashrc")
            print()
            print("  Then type  leanai .")


if __name__ == "__main__":
    main()
