"""
LeanAI · Phase 1 — Self-Improvement Loop
The system that makes LeanAI grow smarter with every interaction.

How it works:
  1. Every exchange is scored (was the answer good? verified? fast?)
  2. High-quality exchanges are stored as training pairs
  3. A background LoRA fine-tuning job runs periodically
  4. The updated adapter is swapped in hot — no restart needed
  5. Repeat forever

This is what separates LeanAI from static frozen models.
After 10,000 interactions it will have learned patterns no
training dataset could have provided.
"""

import json
import time
import hashlib
import threading
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional
from enum import Enum


class FeedbackSignal(Enum):
    EXCELLENT   = 5    # verified correct + fast + user approved
    GOOD        = 4    # correct, not verified
    NEUTRAL     = 3    # no feedback
    POOR        = 2    # user indicated error or asked for correction
    WRONG       = 1    # verifier proved incorrect


@dataclass
class TrainingPair:
    """A single (input, output) pair with quality metadata."""
    id: str
    instruction: str
    response: str
    feedback: FeedbackSignal
    confidence: float
    verified: bool
    latency_ms: float
    tier_used: str
    timestamp: float
    source: str = "user_interaction"
    tags: list = field(default_factory=list)

    @property
    def quality_score(self) -> float:
        """0.0–1.0 composite quality score for training prioritization."""
        base = self.feedback.value / 5.0
        conf_bonus = self.confidence * 0.1
        verify_bonus = 0.1 if self.verified else 0.0
        speed_bonus = min(0.05, 500.0 / max(self.latency_ms, 1))
        return min(1.0, base + conf_bonus + verify_bonus + speed_bonus)

    @property
    def is_high_quality(self) -> bool:
        return self.quality_score >= 0.75 and self.feedback.value >= 4


@dataclass
class SelfPlayPair:
    """Generated by self-play: model generates a problem + its own solution."""
    id: str
    domain: str         # "math" | "code" | "reasoning" | "factual"
    problem: str
    solution: str
    verified: bool
    difficulty: float   # 0.0–1.0
    timestamp: float


class TrainingDataStore:
    """
    Persistent store for training pairs.
    Grows with every interaction. Never deletes verified-correct pairs.
    """

    def __init__(self, path: str = "~/.leanai/training"):
        self.path = Path(path).expanduser()
        self.path.mkdir(parents=True, exist_ok=True)
        self._pairs: dict[str, TrainingPair] = {}
        self._self_play: dict[str, SelfPlayPair] = {}
        self._load()

    def add_pair(
        self,
        instruction: str,
        response: str,
        feedback: FeedbackSignal = FeedbackSignal.NEUTRAL,
        confidence: float = 0.5,
        verified: bool = False,
        latency_ms: float = 0.0,
        tier_used: str = "full",
        tags: list = None,
    ) -> TrainingPair:
        pair_id = hashlib.md5(f"{instruction}{time.time()}".encode()).hexdigest()[:16]
        pair = TrainingPair(
            id=pair_id,
            instruction=instruction,
            response=response,
            feedback=feedback,
            confidence=confidence,
            verified=verified,
            latency_ms=latency_ms,
            tier_used=tier_used,
            timestamp=time.time(),
            tags=tags or [],
        )
        self._pairs[pair_id] = pair
        self._save()
        return pair

    def update_feedback(self, pair_id: str, feedback: FeedbackSignal):
        if pair_id in self._pairs:
            self._pairs[pair_id].feedback = feedback
            self._save()

    def get_training_batch(
        self,
        min_quality: float = 0.75,
        max_pairs: int = 1000,
        balanced: bool = True,
    ) -> list[TrainingPair]:
        """
        Return a high-quality training batch.
        Prioritizes verified, excellent, and diverse pairs.
        """
        qualified = [p for p in self._pairs.values()
                     if p.quality_score >= min_quality]

        # Sort by quality descending
        qualified.sort(key=lambda p: p.quality_score, reverse=True)

        if balanced:
            # Balance across tiers and domains
            by_tier: dict = {}
            for p in qualified:
                by_tier.setdefault(p.tier_used, []).append(p)
            result = []
            while len(result) < max_pairs and any(by_tier.values()):
                for tier_pairs in by_tier.values():
                    if tier_pairs and len(result) < max_pairs:
                        result.append(tier_pairs.pop(0))
            return result
        else:
            return qualified[:max_pairs]

    def stats(self) -> dict:
        pairs = list(self._pairs.values())
        if not pairs:
            return {"total": 0, "high_quality": 0, "verified": 0,
                    "avg_quality": 0.0, "by_feedback": {}}

        by_feedback = {}
        for p in pairs:
            key = p.feedback.name
            by_feedback[key] = by_feedback.get(key, 0) + 1

        return {
            "total": len(pairs),
            "high_quality": sum(1 for p in pairs if p.is_high_quality),
            "verified": sum(1 for p in pairs if p.verified),
            "avg_quality": round(sum(p.quality_score for p in pairs) / len(pairs), 3),
            "by_feedback": by_feedback,
            "self_play_pairs": len(self._self_play),
        }

    def _save(self):
        pairs_file = self.path / "pairs.jsonl"
        with open(pairs_file, "w") as f:
            for pair in self._pairs.values():
                d = asdict(pair)
                d["feedback"] = pair.feedback.value
                f.write(json.dumps(d) + "\n")

    def _load(self):
        pairs_file = self.path / "pairs.jsonl"
        if pairs_file.exists():
            with open(pairs_file) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        d = json.loads(line)
                        d["feedback"] = FeedbackSignal(d["feedback"])
                        pair = TrainingPair(**d)
                        self._pairs[pair.id] = pair
                    except Exception:
                        pass


class SelfPlayEngine:
    """
    Generates synthetic training data through self-play.
    The model creates its own problems, solves them, and verifies the solutions.
    High-quality verified solutions become training data.

    Domains:
      MATH     — generate arithmetic/algebra problems with exact solutions
      CODE     — generate small coding challenges with testable solutions
      REASONING — generate logical puzzles with step-by-step solutions
    """

    MATH_TEMPLATES = [
        ("arithmetic", "What is {a} {op} {b}?", "{result}"),
        ("percentage", "What is {pct}% of {n}?", "{result}"),
        ("area", "What is the area of a rectangle {w} × {h}?", "{result}"),
        ("prime", "Is {n} a prime number?", "{result}"),
    ]

    def generate_math_pair(self) -> Optional[SelfPlayPair]:
        """Generate a math problem + verified answer."""
        import random
        import math as mathmod

        templates = [
            self._gen_arithmetic,
            self._gen_percentage,
            self._gen_geometry,
        ]
        gen_fn = random.choice(templates)
        return gen_fn()

    def generate_batch(self, n: int = 10) -> list[SelfPlayPair]:
        """Generate n self-play pairs."""
        pairs = []
        for _ in range(n):
            pair = self.generate_math_pair()
            if pair:
                pairs.append(pair)
        return pairs

    def _gen_arithmetic(self) -> SelfPlayPair:
        import random
        ops = [
            ('+', lambda a, b: a + b),
            ('-', lambda a, b: a - b),
            ('*', lambda a, b: a * b),
        ]
        a = random.randint(2, 999)
        b = random.randint(2, 999)
        op_sym, op_fn = random.choice(ops)
        result = op_fn(a, b)

        problem  = f"What is {a} {op_sym} {b}?"
        solution = f"The answer is {result}.\n\nStep by step:\n{a} {op_sym} {b} = {result}"

        return SelfPlayPair(
            id=hashlib.md5(problem.encode()).hexdigest()[:12],
            domain="math",
            problem=problem,
            solution=solution,
            verified=True,
            difficulty=min(1.0, max(a, b) / 1000.0),
            timestamp=time.time(),
        )

    def _gen_percentage(self) -> SelfPlayPair:
        import random
        pct = random.choice([5, 10, 15, 20, 25, 30, 40, 50, 75])
        n   = random.randint(10, 10000)
        result = n * pct / 100

        problem  = f"What is {pct}% of {n}?"
        solution = f"The answer is {result}.\n\n{pct}% of {n} = ({pct}/100) × {n} = {result}"

        return SelfPlayPair(
            id=hashlib.md5(problem.encode()).hexdigest()[:12],
            domain="math",
            problem=problem,
            solution=solution,
            verified=True,
            difficulty=0.3,
            timestamp=time.time(),
        )

    def _gen_geometry(self) -> SelfPlayPair:
        import random, math as m
        shape = random.choice(["rectangle", "circle", "triangle"])

        if shape == "rectangle":
            w = random.randint(2, 50)
            h = random.randint(2, 50)
            area = w * h
            problem  = f"What is the area of a rectangle with width {w} and height {h}?"
            solution = f"Area = width × height = {w} × {h} = {area} square units."

        elif shape == "circle":
            r = random.randint(1, 20)
            area = round(m.pi * r * r, 4)
            problem  = f"What is the area of a circle with radius {r}?"
            solution = f"Area = π × r² = π × {r}² = π × {r*r} ≈ {area} square units."

        else:
            b = random.randint(4, 40)
            h = random.randint(4, 40)
            area = b * h / 2
            problem  = f"What is the area of a triangle with base {b} and height {h}?"
            solution = f"Area = (base × height) / 2 = ({b} × {h}) / 2 = {b*h} / 2 = {area} square units."

        return SelfPlayPair(
            id=hashlib.md5(problem.encode()).hexdigest()[:12],
            domain="math",
            problem=problem,
            solution=solution,
            verified=True,
            difficulty=0.4,
            timestamp=time.time(),
        )


class LoRATrainer:
    """
    Phase 1: Stub for the LoRA continuous fine-tuning loop.
    Phase 3 will implement the full training pipeline.

    This class manages the training schedule and data preparation.
    Actual training in Phase 3 uses HuggingFace PEFT + bitsandbytes.
    """

    def __init__(self, store: TrainingDataStore):
        self.store = store
        self.last_train_time = 0.0
        self.train_interval_hours = 24.0
        self.min_pairs_to_train = 100
        self._training_thread: Optional[threading.Thread] = None

    def should_train(self) -> bool:
        """Check if it's time to run a training cycle."""
        stats = self.store.stats()
        time_since = (time.time() - self.last_train_time) / 3600
        return (
            stats["high_quality"] >= self.min_pairs_to_train
            and time_since >= self.train_interval_hours
        )

    def prepare_training_data(self, output_path: str = "~/.leanai/training/batch.jsonl"):
        """Export high-quality pairs in instruction-tuning format."""
        path = Path(output_path).expanduser()
        batch = self.store.get_training_batch(min_quality=0.75, max_pairs=2000)

        with open(path, "w") as f:
            for pair in batch:
                record = {
                    "instruction": pair.instruction,
                    "output": pair.response,
                    "quality": round(pair.quality_score, 3),
                    "verified": pair.verified,
                }
                f.write(json.dumps(record) + "\n")

        print(f"[LoRA] Training data prepared: {len(batch)} pairs → {path}")
        return path

    def training_plan(self) -> dict:
        """Return the training configuration for Phase 3."""
        return {
            "method": "LoRA",
            "rank": 16,
            "alpha": 32,
            "target_modules": ["q_proj", "v_proj"],
            "learning_rate": 2e-4,
            "batch_size": 4,
            "gradient_accumulation": 4,
            "max_steps": 500,
            "warmup_steps": 50,
            "save_steps": 100,
            "eval_steps": 50,
            "fp16": True,
            "note": "Phase 3 will implement this fully with PEFT + bitsandbytes",
        }
